### ISSUE TITLE
Add license to software?

### ISSUE THREAD

**Issue by austinhpatton** [almeidasilvaf/cogeqc#1]
Hi there - first of all, thank you for putting together this package! I'm currently using it to assess orthogroup inference quality and it's been a fantastic tool. 

I was looking to see whether the software included a license, and I noticed that you haven't yet added one - I was wondering whether you might be willing to do so?

Thanks again!
Austin

**Comment by almeidasilvaf** [comment]
Hi, @austinhpatton 

Thank you for your feedback!

The package is licensed under GPL-3. All Bioconductor packages are required to have a license, which is specified in the "License:" field of the DESCRIPTION file (see here: https://github.com/almeidasilvaf/cogeqc/blob/master/DESCRIPTION#L25).

I will add a LICENSE.md file with the license text to make it more visible.

Best,
Fabricio

**Comment by austinhpatton** [comment]
Hi Fabricio,

My apologies for having missed that - it was right in front of me! And yes, a license on the repository would help provide that immediate clarity, but I appreciate your prompt response!

Thanks again,
Austin
